## Day Agenda
- Data science Life cycle 
- Data science Libraries


## Data science Life cycle 
Involves 6-7 steps
1. Business Understanding
2. Data Preparation
3. Data Munging/Data Wrangling
    - feature selection
    - EDA Tool
4. Model training
5. Model Evalution
6. Model Deployment
    - aws
    - IBM waston studio
7. Model tracking



## Data Analysis Libraries
- Numpy
- Pandas
- Matplotlib
- Seaborn
- scipy


## Numpy
- Numerical Python
- Developed in 2005 by Travis oliphant
- Create arrays
    - zero dimensional array
    - Single dimensional array
    - Two dimensional array
    - Multi dimensional array

- linear algrbra ,Fourier Transforms,materics


In [1]:
import numpy

In [2]:
pip  install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
np.__version__

'1.19.2'

##  Creating array's

In [5]:
import numpy as np
x=np.array(23)
print(x)

23


In [6]:
## check the dimension
np.ndim(x)

0

In [8]:
## 1-D array
x1=np.array([12,23,4,5,6])
print(x1)
print(np.ndim(x1))

[12 23  4  5  6]
1


In [13]:
## 2D-Array
x2=np.array([[1,2,3],[1,3,4]])
print(x2)
print("Dimension of x2:",np.ndim(x2))

[[1 2 3]
 [1 3 4]]
Dimension of x2: 2


In [15]:
## To get the number of elements in x2 array
np.size(x2)

6

In [17]:
## To get no rows and columns
np.shape(x2)

(2, 3)

## 3D-Array
 

In [18]:
import numpy as np
x3= np.array([[[1,2,3],[6,7,8],[6,11,33]]])
print(x3)
print("dimension of x3:",np.ndim(x3))
print("elements of x3:",np.size(x3))
print("shape of x3:",np.shape(x3))

[[[ 1  2  3]
  [ 6  7  8]
  [ 6 11 33]]]
dimension of x3: 3
elements of x3: 9
shape of x3: (1, 3, 3)


## Methods to craete arrays
- Zeros
- Ones
- linspace
- logspace
- arange
- random.rand

In [26]:
a0=np.zeros(4,dtype=int)
a0

array([0, 0, 0, 0])

In [29]:
a1=np.ones(5,dtype=int)
a1

array([1, 1, 1, 1, 1])

In [32]:
a1=np.ones(5,dtype=int)
print("a1:",a1)
a2=a1.reshape(5,1)
print("reshape of a1 into a2:",a2)
a3=a1.reshape(1,5)
print("reshape of a1 to a3:",a3)

a1: [1 1 1 1 1]
reshape of a1 into a2: [[1]
 [1]
 [1]
 [1]
 [1]]
reshape of a1 to a3: [[1 1 1 1 1]]


In [38]:
a=np.arange(1,12,2)
print(a)
print("Dimension :",np.ndim(a))
print("Elements:",np.size(a))

[ 1  3  5  7  9 11]
Dimension : 1
Elements: 6


# Possibilities to reshape of 6 elements
- (2,3)
- (3,2)
- (6,1)
- (1,6)


In [44]:
a1=a.reshape(3,2)
print(a)
print(a1)

[ 1  3  5  7  9 11]
[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [51]:
l1=np.logspace(1,5,1)
print(l1)

[10.]


In [54]:
l2=np.linspace(1,5)
l2

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [56]:
l2=np.linspace(1,5,6)
l2

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [61]:
r=np.random.rand(3,2)
r

array([[0.27101441, 0.28214413],
       [0.3713502 , 0.9384794 ],
       [0.08958277, 0.94310986]])

In [64]:
r1=np.random.randint(1,100)
r1

96

In [66]:
r2=np.random.randn(1,10)
r2

array([[ 1.15213469,  0.16523442,  0.78574941, -1.25257628, -2.3504616 ,
        -0.95729881, -0.25490902,  0.77085751,  1.19840478, -0.80756149]])

In [67]:
np.ndim(r2)

2

In [69]:
r3=r2.flatten()
r3

array([ 1.15213469,  0.16523442,  0.78574941, -1.25257628, -2.3504616 ,
       -0.95729881, -0.25490902,  0.77085751,  1.19840478, -0.80756149])

In [70]:
np.ndim(r3)

1

## Accessing Elements in Arrays
1. indexing
    - +ve 
    - -ve
2. Slicing
    -[start:stop:step]
3. Loop
    - for
    - while